name: Build and test with Bazel

on:
  push:
    branches: [ master,bazel ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: java --version && ./bazelisk test //... --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
