name: Build and test with Bazel

on:
  push:
    branches: [ master,bazel ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./bazelisk test //...
