name: Google Java Formatter

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--replace"
