name: Maven Publish

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /tmp/bazel
        key: ${{ runner.os }}-bazel-cache
    - name: Build
      run: mkdir -p /tmp/bazel && bazel run --stamp --define "maven_repo=https://api.bintray.com/maven/birdayz/oss-releases/kafka-streams-contrib/%3Bpublish=1" --define "maven_user=birdayz" --define "maven_password=${{ JCENTER_TOKEN }}" //:library-export.publish
